# -*- coding: utf-8 -*-
"""Age_Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bOrCYZAumFPPoWNCq4Ms2WFzXwS0sVPu
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st

st.title("Age Calculator")

dob = st.date_input("select DOB")

if st.button("Calculate"):
  today=date.today()
  age=today.year-dob.year

  st.success(f"Age: {age} years")

